import type { FastifyInstance } from 'fastify';
import { registerStatsRoutes } from './stats';
import { registerRftRoutes } from './rft';
import { registerSyncPerformanceRoutes } from './sync-performance';
import { registerNotesRoutes } from './notes';
import { registerIngestionRoutes } from './ingestion';
import { registerCompaniesRoutes } from './companies';
import { registerFreshdeskWebhookRoutes } from './freshdesk-webhook';
import { registerEngineerHoursRoutes } from './engineer-hours';
import { registerSettingsRoutes } from './settings';
import { registerGoogleSheetsRoutes } from './google-sheets';
import { registerGroupsRoutes } from './groups';
import { registerQuickAnswersRoutes } from './quick-answers';
import { registerMonthlyReportRoutes } from './monthly-report';
import { registerLiveStatsRoutes } from './live-stats';
import { registerAiChatRoutes } from './ai-chat';
import { registerErrorLogRoutes } from './error-logs';
import { registerYtdIngestionRoutes } from './ytd-ingestion';
import { registerAppDataRoutes } from './app-data';
import { registerYearRoutes } from './years';
import { registerAuditLogRoutes } from './audit-logs';
import { registerCleanupRoutes } from './cleanup';
import { registerLeadershipRoutes } from './leadership';
import { registerTicketRoutes } from './leadership/tickets';
import { registerMetabaseImplementationsRoutes } from './metabase-implementations';
import { registerMetabaseEmbedRoutes } from './metabase-embed';
import { registerEnvironmentSettingsRoutes } from './environment-settings';
import shareLinksRoutes from './share-links';
import { pdfRoutes } from './pdf';

export async function registerRoutes(fastify: FastifyInstance): Promise<void> {
  await registerStatsRoutes(fastify);
  await registerRftRoutes(fastify);
  await registerSyncPerformanceRoutes(fastify);
  await registerNotesRoutes(fastify);
  await registerIngestionRoutes(fastify);
  await registerCompaniesRoutes(fastify);
  await registerFreshdeskWebhookRoutes(fastify);
  await registerEngineerHoursRoutes(fastify);
  await registerSettingsRoutes(fastify);
  await registerGoogleSheetsRoutes(fastify);
  await registerGroupsRoutes(fastify);
  await registerQuickAnswersRoutes(fastify);
  await registerMonthlyReportRoutes(fastify);
  await registerLiveStatsRoutes(fastify);
  await registerAiChatRoutes(fastify);
  await registerErrorLogRoutes(fastify);
  await registerYtdIngestionRoutes(fastify);
  await registerAppDataRoutes(fastify);
  await registerYearRoutes(fastify);
  await registerAuditLogRoutes(fastify);
  await registerCleanupRoutes(fastify);
  await registerLeadershipRoutes(fastify);
  await registerTicketRoutes(fastify);
  await registerMetabaseImplementationsRoutes(fastify);
  await registerMetabaseEmbedRoutes(fastify);
  await registerEnvironmentSettingsRoutes(fastify);
  await shareLinksRoutes(fastify);
  await pdfRoutes(fastify);
}
